name: radar_nowcasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pysteps
  - matplotlib
  - numpy
  - pytorch
  - torchvision
  - torchmetrics
  - requests
  - h5py
  - streamlit